name: Build

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          submodules: recursive

      - name: Install dependencies
        run: npm install

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y fonttools fontforge python3-fontforge inkscape

      - name: Build
        run: make

      - name: Upload TTF
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: build/Twemoji Mozilla.ttf
          archive: false

  release:
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/v')

    needs: build

    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1

      - name: Rename TTF
        run: mv 'Twemoji Mozilla.ttf' TwemojiMozilla.ttf

      - name: Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          files: TwemojiMozilla.ttf
